variables:
  NEXUS_USER: ""
  NEXUS_PASSWORD: ""
  NEXUS_CHARTS_URL: "https://nexus.corp.pushwoosh.com/repository/helm-charts/"
  BITNAMI_REPO_URL: "https://charts.bitnami.com/bitnami"

helm:package:
  image: $CI_REGISTRY/docker/alpine-ci
  stage: build
  script:
    - helm repo add bitnami $BITNAMI_REPO_URL
    - helm repo list
    - export CHART_NAME=$(awk '/name:/{print $NF; exit}' Chart.yaml)
    - printenv CHART_NAME
    - export PKG=$(helm package --dependency-update --save=false --version=$CI_COMMIT_TAG . | grep \.tgz | cut -d":" -f2)
    - printenv PKG
    - curl -sSf -u $NEXUS_USER:$NEXUS_PASSWORD $NEXUS_CHARTS_URL --upload-file $PKG
  only:
    refs:
      - tags
