apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  labels:
    app: clickhouse-config
data:
  system.xml: |-
    <yandex>
      <listen_host>::</listen_host>
    </yandex>
  remote_servers.xml: |-
    <yandex>
      <remote_servers incl="clickhouse_remote_servers" replace="replace">
        <clicks_cluster>
          <shard>
            <internal_replication>true</internal_replication>
            {{range $i, $e := until (atoi (printf "%d" (int64 .Values.clickhouse.replicaCount))) }}
            <replica>
                <default_database>default</default_database>
                <host>clickhouse-{{$i}}.clickhouse</host>
                <port>9000</port>
            </replica>
            {{end}}
          </shard>
        </clicks_cluster>
      </remote_servers>
    </yandex>
  users.xml: |-
    <yandex>
      <profiles>
        <default>
          <max_memory_usage>10000000000</max_memory_usage>
          <use_uncompressed_cache>0</use_uncompressed_cache>
          <load_balancing>random</load_balancing>
        </default>
      </profiles>
      <users replace="replace">
        <default>
          <password>{{ .Values.clickhouse.password }}</password>
          <profile>{{ .Values.clickhouse.user }}</profile>
          <quota>default</quota>
          <networks>
            <ip>::/0</ip>
          </networks>
        </default>
      </users>
    </yandex>
  zookeeper.xml: |-
    <yandex>
    {{ if .Values.zookeeper.enabled }}
      <zookeeper incl="zookeeper-servers" replace="replace">
      {{range $i, $zk := until (atoi (printf "%d" (int64 .Values.zookeeper.replicaCount))) }}
        <node>
            <host>clickhouse-zookeeper-{{$i}}.clickhouse-zookeeper-headless</host>
            <port>2181</port>
        </node>
      {{end}}
      </zookeeper>
    {{ else if .Values.externalZookeeper.enabled }}
    <zookeeper incl="zookeeper-servers" replace="replace">
    {{ range .Values.externalZookeeper.servers }}
      <node>
          <host>{{ . }}</host>
          <port>2181</port>
      </node>
    {{ end }}
    </zookeeper>
    {{ end }}
    </yandex>
